sagan-common/src/main/java/sagan/team/support/TeamService.java, sagan-site/src/main/resources/templates/admin/team/edit.html
* Added checkbox at bottom of /admin/team/{username} allowing anyone to toggle a person's hidden status
* Verified through visual testing
* Tried to fix order of imports at top of TeamService, but IntelliJ keeps undoing my re-organize imports
=> Add ability to manage Spring Alumni

sagan-indexer/src/main/resources/application.yml, sagan-site/src/main/resources/application.yml
See https://spring.io/info
```json
{
"build": {
"version": "X.X.X.X",
"artifact": "spring-io",
"description": "spring-io",
"name": "spring-io"
},
"app": {
"name": "sagan-blue:0",
"start": "2015-01-26 01:45:20 +0000"
},
"spring": {
"profiles": "production"
},
"git": {
"branch": "detached HEAD",
"commit": {
"id": "cbbe743",
"time": "2015-01-14 11:09"
}
}
}
```
=> remove "version: X.X.X.X" from application info

sagan-common/src/main/java/sagan/blog/support/BlogService.java, sagan-common/src/main/java/sagan/blog/support/PostRepository.java
See https://github.com/spring-projects/spring-boot/issues/2730#issuecomment-90278175
=> Fix blog repository not ordering results

sagan-site/src/main/resources/templates/admin/blog/_post_form.html
Natural class attribute is overwritten by th:class. Opted to leverage
the natural class attribute and th:classappend for errors.
=> leveraged th:classappend to fix dead code

sagan-site/src/it/java/sagan/projects/support/ProjectsMetadataApiTests.java, sagan-site/src/main/java/sagan/projects/support/JsonPControllerAdvice.java, sagan-site/src/main/java/sagan/projects/support/ProjectMetadataController.java, sagan-site/src/main/java/sagan/support/JsonPController.java
See [SPR-8346](https://jira.spring.io/browse/SPR-8346)
=> use JSONP support in projectmetadata controller

sagan-site/src/main/resources/templates/projects/index.html
Should clarify that page to show:
* projects maintained by the Spring team
* community projects
* projects in incubation
* projects in the attic
=> clarify /projects page

sagan-site/src/main/resources/templates/team/show.html
Look at the team members in a phone. My head looks like it's being squashed. And the blog text overlaps the Twitter feed.
=> Team pages not rendering correctly in phone

sagan-client/build.gradle
See https://plugins.gradle.org/plugin/com.moowork.node
=> Use gradle plugin for Node.js build

sagan-common/src/main/java/sagan/projects/ProjectRelease.java, sagan-common/src/test/java/sagan/projects/ProjectReleaseVersionTests.java
http://projects.spring.io/spring-data
=> Release candidates invalidly marked as GA version

sagan-indexer/src/main/resources/application.yml, sagan-site/src/main/resources/application.yml
Logging is now done using a SaaS service
=> don't write to log files in production

sagan-site/src/it/java/saganx/AbstractIntegrationTests.java, sagan-site/src/it/java/saganx/AuthorizationTests.java, sagan-site/src/main/java/sagan/SecurityConfig.java, sagan-site/src/main/resources/templates/blog/_full_post.html
This commit adds an edit link to blog posts if the user is authenticated.
This makes it easier to modify a post when viewing it from the public
website.
=> Add Blog Edit Link for Authenticated Users

sagan-site/src/main/resources/templates/pages/index.html
=> Update spring.io rotating banner for brixton release

sagan-site/src/main/resources/templates/tools/sts/all.html
this updates the update site URLs in combination with the 3.8.0.RELEASE
=> need to update the list of update site URLs

sagan-site/src/main/java/sagan/blog/support/PostView.java
=> Fix tests when default Locale is not US

sagan-site/src/main/resources/templates/pages/index.html
Updating Automate Ops for Spring Cloud on Cloud Foundry URL
=> Fixes Issue#697 update existing hero banner

sagan-common/src/main/java/sagan/projects/Project.java, sagan-site/src/it/java/sagan/projects/support/ProjectsMetadataApiTests.java, sagan-site/src/main/java/sagan/projects/support/ProjectAdminController.java, sagan-site/src/main/java/sagan/projects/support/ProjectMetadataController.java
The whole project can be updated including all its releases by
a PUT (instead of a POST of each release you want to change)
=> Add support for PUT /project_metadata/{projectId}

sagan-common/src/main/java/sagan/projects/ProjectRelease.java
@dsyer Please review this change.
=> spring-io#732 fix

sagan-site/src/main/resources/templates/tools/sts/all.html
changed from dist to download to benefit from CDN caching and reducing direct traffic to S3
=> changed p2 repo URLs from dist to download

sagan-site/src/main/resources/templates/blog/_right-pane.html, sagan-site/src/main/resources/urlrewrite.xml, sagan-site/src/test/java/sagan/rewrite/support/RewriteTests.java
Current LinkedIn user group urls are broken. This fixes the urls.
=> Fixes #862, fix LinkedIn urls

sagan-common/src/main/java/sagan/SaganApplication.java, sagan-site/src/main/resources/application.yml
=> Add client.dir in standalone profile

sagan-site/src/main/resources/templates/layout.html, sagan-site/src/main/resources/templates/pages/batch.html, sagan-site/src/main/resources/templates/pages/cloud.html, sagan-site/src/main/resources/templates/pages/microservices.html, sagan-site/src/main/resources/templates/pages/reactive.html, sagan-site/src/main/resources/templates/pages/serverless.html, sagan-site/src/main/resources/templates/pages/streams.html, sagan-site/src/main/resources/templates/pages/webapps.html
This pull request adds the new static pages linked under "Why Spring" menu
=> add all new linked pages under menu Why Spring

sagan-site/src/main/resources/templates/blog/index.html, sagan-site/src/main/resources/templates/guides/gs/guide.html, sagan-site/src/main/resources/templates/guides/index.html, sagan-site/src/main/resources/templates/layout.html, sagan-site/src/main/resources/templates/pages/community.html, sagan-site/src/main/resources/templates/pages/events.html, sagan-site/src/main/resources/templates/pages/index.html, sagan-site/src/main/resources/templates/pages/learn.html, sagan-site/src/main/resources/templates/pages/quickstart.html, sagan-site/src/main/resources/templates/pages/support.html, sagan-site/src/main/resources/templates/pages/training.html, sagan-site/src/main/resources/templates/pages/whyspring.html, sagan-site/src/main/resources/templates/projects/index.html, sagan-site/src/main/resources/templates/projects/show.html
refreshing all templates from springio repo
=> refresh static templates

sagan-site/src/main/resources/templates/layout.html
So Spring Cloud comes before Spring Cloud Data Flow. Feels more logical.
=> changed the order of the projects in the dropdown

sagan-site/src/main/resources/templates/tools/list.html
fix for copy/paste mistake introduced in 4da89065cf1d62f7304196e0dd8394c9c0f0caa0
=> fixed duplicated copy text for navigation feature

CONTRIBUTING.md
pull-request is hub's command, not git's. Example was wrong.
More examples of using `hub pull-request` from hub documentation: https://hub.github.com/hub-pull-request.1.html
=> Update hub usage example

sagan-site/src/main/resources/templates/pages/training.html
=> Add Spring Security training
