spring-io/sagan

sagan-site/src/main/resources/templates/pages/platform.html

Please remove this text right at the top:
A detailed list of modules and versions included in the forthcoming Spring IO platform initial release will be available soon.
and replace with:
Click here[1] for a detailed list of modules and versions that are included in the Spring IO platform distribution.
[1] http://docs.spring.io/platform/docs/current/reference/htmlsingle/#appendix-dependency-versions

minor copy update to spring.io/platform

---

sagan-site/src/main/resources/templates/admin/blog/_post_form.html

because of previous limitations with github's markdown engine (with rendering of some html tags), we had to implement workarounds.
Now that we have a complete markdown engine, all html tags are allowed and so those workarounds should be removed (implementation + documentation in UI).

remove outdated syntax hint for markdown

---

sagan-site/src/main/resources/urlrewrite.xml
sagan-site/src/test/java/sagan/rewrite/support/RewriteTests.java

update https://spring.io/guides/gs/convert-jar-to-war-maven/ so that it simply redirects to https://spring.io/guides/gs/convert-jar-to-war/? The latter now covers both.

add a redirect from jar/war guide

---

sagan-common/src/main/java/sagan/tools/support/ToolSuiteXml.java
sagan-common/src/main/java/sagan/tools/support/ToolXmlConverter.java
sagan-common/src/main/java/sagan/tools/support/ToolsService.java
sagan-common/src/test/java/sagan/tools/support/ToolSuiteXmlParsingTests.java
sagan-common/src/test/java/sagan/tools/support/ToolXmlConverter_SingleArchiveDownloadTests.java
sagan-common/src/test/java/sagan/tools/support/ToolXmlConverter_SingleLegacyDownloadTests.java
sagan-site/src/it/java/sagan/tools/support/ToolsPagesTests.java
sagan-site/src/main/java/sagan/tools/support/ToolsController.java
sagan-site/src/main/resources/templates/tools/sts/all.html
sagan-site/src/main/resources/templates/tools/sts/legacy.html

We are constantly getting questions where to find older versions of STS/GGTS for download. This was available on the old website, but hasn't been ported over to the new STS/GGTS download pages. I think we need to bring this back now, since too many people are asking for this.

old STS/GGTS versions should be available for download

---

sagan-client/src/app/main.js
sagan-client/src/feature/courseware/main.js
sagan-common/src/main/java/sagan/guides/support/AsciidoctorUtils.java
sagan-site/src/main/resources/templates/guides/gs/guide.html

This change adds Pivotal Education links in the sidebar.
Browsers will send an AJAX request to the LMS website and will get back
relevant courses (depending on the Referer URL).
Note: the same feature is also added on individual projects pages.

Link to Pivotal Education courses in guides

---

sagan-common/src/main/java/sagan/guides/support/GettingStartedGuides.java
sagan-site/src/main/java/sagan/guides/support/DocsWebhookController.java
sagan-site/src/test/java/sagan/guides/support/DocsWebhookControllerTests.java

To make it possible for 3rd party sources of guides and tutorials to send a GitHub hook with the pertinent repository name embedded in the URL itself

Add extra webhook handler

---

sagan-site/src/main/java/sagan/SiteConfig.java
sagan-site/src/main/java/sagan/support/health/ElasticsearchHealthIndicator.java
sagan-site/src/main/resources/application.yml
sagan-site/src/main/resources/elasticsearch/settings.json
util/recreate-elasticsearch-index.sh

This change adds a new HealthIndicator implementation that relies on the
JestClient to get information on the ElasticSearch cluster status.
The ElasticSearch init script has been fixed to initialize the index
with fixed shard/replica values and initialize later settings.
Local deployments don't require SSL anymore to see sensitive health
endpoints.
Fixes #551

Add ElasticSearch health indicator

---

sagan-site/src/main/java/sagan/SiteConfig.java

if the initParameter confPath on SiteConfig is "urlrewrite.xml" then, when the application start some exceptions occurs. I saw that the path was updated to "/urlrewrite.xml" and after that, there's no exceptions on startup. But in fact, the UrlRewriteFilter class doesn't found urlrewrite.xml file anymore.  
e.g: try to access https://spring.io/videos and you'll see that there's no redirection to http://www.youtube.com/springsourcedev

UrlRewriting doesn't function 

---

sagan-common/src/main/java/sagan/projects/ProjectRelease.java
sagan-common/src/test/java/sagan/projects/ProjectReleaseVersionTests.java
sagan-common/src/test/java/sagan/projects/ProjectVersionDisplayNameTests.java
sagan-common/src/test/java/sagan/search/support/SearchServiceTests.java

Simplifies the parsing of a version to determine the "display name". It
didn't really need a regex, and the regex made it hard to match on
"release train" names (like in Spring Data or Spring Cloud)
Fixes gh-562

Change parsing of release versions

---

sagan-common/src/main/java/sagan/projects/ProjectRelease.java
sagan-common/src/main/java/sagan/projects/ProjectRepository.java
sagan-common/src/test/java/sagan/projects/ProjectReleaseVersionTests.java

The logic was duplicated in ProjectRelease and ProjectRepository.
This change consolidates it in ProjectRelease so that the repository
metadata is correct in all ProjectReleases (even those that do not
end in "RELEASE").
Fixes gh-565

Fix logic for detecting version types (milestone/snapshot)

---

sagan-site/src/main/resources/templates/tools/sts/all.html

removed outdated update sites and GGTS from description, but not sure if this is the right place to change this

updated STS download page for 3.7.0 release

---

sagan-common/src/test-util/java/sagan/projects/ProjectReleaseBuilder.java
sagan-common/src/test/java/sagan/projects/ProjectReleaseVersionTests.java

This change is only in test code, just tidying up the 
ProjectReleaseBuilder utility a bit so that it actually
uses the releease status detection logic by default.

Remove redundant default release version

---

sagan-site/src/main/resources/urlrewrite.xml
sagan-site/src/test/java/sagan/rewrite/support/RewriteTests.java

http://spring.io/guides/gs/spring-xd-osx/ is a broken link.  I'm assuming it should be redirected here: http://spring.io/guides/gs/spring-xd

Broken link (http://spring.io/guides/gs/spring-xd-osx/)

---

sagan-common/src/main/java/sagan/search/support/SaganQueryBuilders.java
sagan-common/src/main/java/sagan/search/support/SpringFacetsBuilder.java
sagan-common/src/main/java/sagan/search/types/ProjectPage.java
sagan-common/src/main/java/sagan/search/types/SearchEntry.java
sagan-common/src/main/java/sagan/search/types/SearchType.java
sagan-common/src/test-util/java/sagan/search/support/SearchEntryBuilder.java
sagan-common/src/test/resources/fulltext-query.json
sagan-indexer/src/it/java/sagan/IndexSchedulerTests.java
sagan-indexer/src/main/java/sagan/IndexScheduler.java
sagan-indexer/src/main/java/sagan/projects/support/GithubPagesSearchEntryMapper.java
sagan-indexer/src/main/java/sagan/projects/support/ProjectPagesIndexer.java
sagan-indexer/src/main/resources/application.yml
sagan-indexer/src/test/java/sagan/projects/support/ProjectPagesIndexerTests.java
sagan-site/src/it/java/sagan/search/support/SearchServiceIntegrationTests.java
sagan-site/src/main/resources/elasticsearch/mappings/projectpage.json
util/recreate-elasticsearch-index.sh

When submitting one of the most popular search queries like "spring boot", one should get the project page as the first result.

Tweak search query to return projects

---

sagan-client/src/css/guide.css
sagan-client/src/css/responsive.css

Guide titles overlap on mobile screens
Guide container width can be set to 100% at mobile breakpoint.

List of Spring guides are difficult to read on mobile

---

sagan-common/src/main/java/sagan/team/support/DefaultTeamImporter.java
sagan-common/src/main/java/sagan/team/support/TeamService.java
sagan-site/src/it/java/sagan/team/support/ImportTeamFromGithubTests.java

The "import team members from github" button in the admin interface does not work properly for several reasons:
* it's only listing the first 30 team members as the "team" GitHub API endpoint is paginated
* it's requesting user profile information with a non-authenticated REST client, thus rate-limited
* it's not updating user profile information (such as name and avatar_url)

update github API re:gravatar

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
sagan-common/build.gradle
sagan-site/src/it/java/sagan/projects/support/ProjectsMetadataApiTests.java

* Upgrade to Spring Boot 1.2.7
* elasticsearch is now a dependency managed by Boot, so we need
to override its version at the IO Platform level
* Spring Framework is now prepending JSONP responses with a "/**/"
prefix
* Upgrade to Gradle 2.8
* various dependency upgrades

Upgrade to Spring IO Platform 1.1.4

---

sagan-common/src/main/java/sagan/projects/Project.java
sagan-common/src/main/java/sagan/projects/ProjectRelease.java
sagan-common/src/test/java/sagan/projects/ProjectVersionOrderTests.java

Issue #594 seems to be occurring because versions are stored as strings and compared as strings - 1.10 is compared to 1.9 as character '1' vs character '9' instead of number '10' vs '9'. This change addresses issue #594 by adding a comparator that cares about numbers and using that comparator whenever we call Project::getProjectReleases.
Two quick notes:
- Not sure if people are comfortable solving this kind of problem through getters. Figured the alternative is to find all places we're using projectReleases and sort - which seems like a lot of duplicated effort - or change the db model to not have version as a string, which seems like a big chore.
- ProjectAdminController - `@RequestMapping(value = "{id}", method = POST) public String save(@Valid Project project... etc` - calls …

Fix issue #594 - version ordering

---

sagan-common/src/main/java/sagan/projects/ProjectRepository.java
sagan-common/src/main/resources/db/migration/V6__update_repository_urls.sql
sagan-site/src/it/java/sagan/projects/support/ProjectsMetadataApiTests.java

Previously, the project pages used http://repo.spring.io/milestone and http://repo.spring.io/snapshot repository URLs in the sample pom.xml and build.gradle snippets for milestone and snapshot versions
of a project. This is problematic as it assumes that all of project's dependencies will be available in the snapshot or milestone repository. This won't always be the case. For example, current Spring Boot 1.4 snapshots depend on Spring Data Hopper M1 which isn't available in the snapshot repository.
This pull request updates the project metadata to use https://repo.spring.io/libs-snapshot and
https://repo.spring.io/libs-milestone. These virtual repositories make content from the more stable repositories, e.g. libs-snapshot provides access to the contents of the snapshot, milestone, and …

Use libs repositories in example pom.xml and build.gradle snippets

---

sagan-site/src/main/resources/templates/_mobile-nav.html

Adds a Doc link to the mobile navigation menu:
Resolves #653

Add Docs link to mobile navigation

---

sagan-common/src/main/java/sagan/blog/PostFormat.java
sagan-common/src/main/java/sagan/blog/support/AsciidoctorMarkdownService.java
sagan-common/src/main/java/sagan/blog/support/FormatAwarePostContentRenderer.java
sagan-common/src/main/java/sagan/blog/support/PostContentRenderer.java
sagan-common/src/main/java/sagan/blog/support/PostFormAdapter.java
sagan-common/src/test/java/sagan/blog/support/AsciidoctorMarkdownServiceTests.java

Code highlighting works. There may be other tweaks to make, but this
seems like an easy change to adopt. I left in the old behaviour as a
profile "original" if needed.
Fixes gh-357

Add support for blogs in asciidoctor

---

sagan-site/src/main/java/sagan/projects/support/BadgeController.java
sagan-site/src/test/java/sagan/projects/support/BadgeControllerTest.java

Use two passes to determine the project release. The first pass checks the release status and the current flag. If no version was found, fall back to the first matching project release according the release status.
Fixes gh-662

Use the most recent version in version badges

---

sagan-common/src/main/java/sagan/projects/ProjectRelease.java
sagan-site/src/it/java/sagan/projects/support/ProjectsMetadataApiTests.java
sagan-site/src/it/java/saganx/AbstractIntegrationTests.java
sagan-site/src/main/java/sagan/SecurityConfig.java
sagan-site/src/main/java/sagan/projects/support/ProjectMetadataController.java
sagan-site/src/main/resources/application.yml

User can GET or delete a release via /{projectId}/{version} or
add/edit a release by POSTing the whole release to /{projectId}.
Authentication is via HTTP Basic with a Github API token (as the
username and an empty password, just like Github native APIs).
All the new endpoints are protected.
Fixes gh-701

Add API endpoints for /project_metadata

---

sagan-common/src/main/java/sagan/projects/Project.java
sagan-common/src/main/java/sagan/projects/ProjectRelease.java
sagan-site/src/main/java/sagan/projects/support/ProjectAdminController.java
sagan-site/src/main/java/sagan/projects/support/ProjectMetadataController.java
sagan-site/src/test/java/sagan/projects/support/ProjectAdminControllerTests.java
sagan-site/src/test/java/sagan/projects/support/ProjectMetadataControllerTests.java

The user sees {version} placholders when she edits a project in UI, but
the database only contains concrete URLs. The API endpoints are a bit
different: a GET returns the concrete URL, but you can POST or
PUT URLs with placeholders to mimic the UI.

Revert to old behaviour with placeholders in UI

---

sagan-common/src/main/java/sagan/projects/ProjectRelease.java
sagan-site/build.gradle
sagan-site/src/docs/asciidoc/index.adoc
sagan-site/src/it/java/sagan/projects/support/ProjectsMetadataApiTests.java
sagan-site/src/it/java/sagan/search/support/InMemoryElasticSearchConfig.java
sagan-site/src/it/java/sagan/search/support/SearchFacetsIntegrationTests.java
sagan-site/src/it/java/sagan/search/support/SearchPageTests.java
sagan-site/src/it/java/sagan/search/support/SearchServiceIntegrationTests.java
sagan-site/src/it/java/sagan/support/SecurityRequestPostProcessors.java
sagan-site/src/it/java/saganx/AbstractIntegrationTests.java
sagan-site/src/it/java/saganx/IntegrationTestsConfig.java
sagan-site/src/main/java/sagan/projects/support/ProjectMetadataController.java
sagan-site/src/main/resources/templates/docs/index.html

Also fixes a bug with PUT /{projectId}/releases where the repository would
not be merged and the endpoint throws an exception (for any request
containing a repository).
Fixes gh-703

Add REST Docs to project metadata

---

sagan-client/package.json
sagan-common/src/main/java/sagan/projects/Project.java
sagan-common/src/main/java/sagan/projects/ProjectRelease.java
sagan-common/src/main/java/sagan/projects/support/Version.java
sagan-common/src/test/java/sagan/projects/ProjectVersionOrderTests.java
sagan-site/src/test/java/sagan/projects/support/BadgeControllerTest.java

Sorts release train names in alphabetically descending order, then considers SR numbers and such secondarily.

Release trains are not properly sorted by name (fixes #716)

---

.travis.yml

In addition to checking whether Travis is building is a PR, also verify that the commit is on the master branch before triggering a deployment.

Verify master branch before deploying

---

sagan-client/src/css/blog.css

- Admonition blocks need a little padding between the "Note" field and the actual content.
- List items don't need padding at the bottom.
- Paragraphs, when inside a list item, don't need margin at the bottom.

Tune blog layout

---

sagan-site/src/main/resources/templates/tools/sts/all.html

since the latest STS 3.9.0 release we don't ship update sites for Eclipse 4.5 anymore

removed STS update site for Eclipse 4.5, no longer supported

---

sagan-site/build.gradle

Otherwise I get integration test failures, but not all the time.

Remove elastic search data in gradle clean

---

.gitignore
sagan-common/src/main/java/sagan/projects/Project.java
sagan-site/src/it/java/sagan/projects/support/ProjectsMetadataApiTests.java

I think this also fixes gh-733, but it's quite hard to test because the
integration tests are all `@Transactional` and the changes are only
persisted on commit (so the error never shows up in tests).

Fix bug with equals() comparison in Project metadata

---

sagan-common/src/main/java/sagan/AsciidoctorConfig.java
sagan-common/src/main/java/sagan/blog/support/AsciidoctorMarkdownService.java
sagan-common/src/main/java/sagan/blog/support/FormatAwarePostContentRenderer.java
sagan-common/src/main/java/sagan/guides/support/GuideOrganization.java
sagan-common/src/test/java/sagan/blog/support/AsciidoctorMarkdownServiceTests.java
sagan-common/src/test/java/sagan/guides/support/DynamicSidebarTests.java
sagan-common/src/test/java/sagan/guides/support/GuidesOrgTests.java
sagan-site/build.gradle
sagan-site/src/it/java/sagan/search/support/InMemoryElasticSearchConfig.java

Asciidoctor and Elasticsearch (embedded) are expensive to
start, especially the first time. This change makes them
lazy or backgrounds the initialization. Startup time goes
down from 8sec to 5sec for me.
Also useful, some JVM command line flags:
```
-noverify -XX:TieredStopAtLevel=1 -Xss256K -Xms16M -Xmx256M -XX:MaxMetaspaceSize=128M -Djava.security.egd=file:/dev/./urandom
```
and switch to Java 8u131-zulu (available via sdkman) - it's faster than the official openjdk build.

Make some expensive initializations happen lazily

---

build.gradle
sagan-site/build.gradle

without this change one can only guess (or read the docs) how the API looks like.
with this change stubs generated from RestDocs tests are created, a JAR is created that can be installed locally (uploaded somewhere?) and can be reused in integration tests (for example here - https://github.com/spring-cloud/spring-cloud-release-tools/issues/22 )

Added integration with Spring Cloud Contract

---

build.gradle
sagan-site/src/it/java/sagan/projects/support/ProjectsMetadataApiTests.java

So that stubs are uniqely identified for GET.
Fixes gh-793

Add query param matcher to project API test

---

sagan-site/src/main/resources/urlrewrite.xml

An old, decomissions REST tutorial resulted in a temporary redirect to `/guides`. The newer REST tutorial (`tut-bookmarks`) has now been rewritten and renamed `tut-rest`, so this old redirect must be removed.

Reinstate REST-based tutorial.

---

sagan-site/src/main/resources/templates/pages/tools.html

STS4 Atom package links point to `boot-java` instead of `spring-boot`

Correct STS4 Atom package links

---

build.gradle
sagan-client/build.gradle

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://issues.gradle.org/browse/GRADLE-1830 migrated to:  
https://issues.gradle.org/browse/GRADLE-1830 ([https](https://issues.gradle.org/browse/GRADLE-1830) result 200).
* http://www.gradle.org/docs/current/userguide/eclipse_plugin.html migrated to:  
https://www.gradle.org/docs/current/userguide/eclipse_plugin.html ([https](https://www.gradle.org/docs/current/userguide/eclipse_plugin.html) result 301).
* http://repo.spring.io/libs-release migrated to: …

URL Cleanup

---

sagan-client/src/css/asciidoctor.css

Came out as the result of the conversation here: https://pivotal.slack.com/archives/C064D3HPZ/p1574414987039400

Code snippets with tab size 4 by default

---

sagan-client/package.json
sagan-client/webpack.config.js

fixing verbose stack Error: sagan@ build: `webpack` issue 
node version v13.9.0
npm version 6.13.7 (also works and for node version 13.2.0)

fix verbose stack Error: sagan@ build: `webpack`

---

sagan-site/src/main/resources/templates/guides/index.html

- Added `guide-search` class to all the guides `div`
and as javascript code is written in a way that it will start considering
these new `div` as well for filtering
Fixes gh-1001
After these changes it filters guides in all three sections, and on filtering it looks something like this
@bclozel is this good ?

Fix bug - Find a guide should filter all the guides

---

sagan-site/src/main/resources/public/.well-known/security.txt
sagan-site/src/main/resources/urlrewrite.xml
sagan-site/src/test/java/sagan/site/support/rewrite/RewriteTests.java

The redirection now points directly to a page describing the security
policy of VMware, rather than a page listing CVEs.
The security.txt is updated to:
1. put the vmware security email as the primary mean of disclosure
2. link to spring.io's (temporary) redirection as an alternative
3. link to the old redirection as a third alternative
4. add a link to a KB page containing PGP public key for secure email
communications when disclosing
5. add an Expires entry to conform to the latest update to the spec

Update the security policy redirection and security.txt

---

sagan-client/src/css/blog.css

Prior to this change the line height in a blog post's bullet list was smaller than in standard paragraphs.
Before:
After:

Consistent line height between standard paragraphs and bullet lists
